# Generated by Django 4.0.4 on 2022-04-29 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=100)),
                ('post_date', models.DateField(auto_now_add=True)),
                ('rating', models.IntegerField(choices=[(0, 'Dont watch'), (1, 'Bad'), (2, 'Average'), (3, 'Good'), (4, 'Great'), (5, 'Outstanding')], default=0)),
                ('review', models.TextField()),
                ('movie_image', models.URLField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewBlogApp.user')),
            ],
        ),
    ]
